[[manager.prepend_keymap]]
on   = "S"
run  = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[[manager.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
# For upcoming Yazi 0.4 (nightly version):
# run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"
[[manager.prepend_keymap]]
on   = "f"
run  = "plugin jump-to-char"
desc = "Jump to char"
