[flavor]
use = "catppuccin-mocha"
# For upcoming Yazi 0.4 (nightly version):
dark = "catppuccin-mocha"
[icon]
prepend_dirs = [
	{ name = "Git", text = "󰊢" },
	{ name = "dotfiles", text = "" },
	{ name = "reveal", text = "󰐨" },
	{ name = "Templates", text = "" },
	{ name = "steam", text = "" },
	{ name = "nextcloud", text = "" }
]
